# Site settings
title: pXart
email: markuspawellek@gmail.com
description: >
  Packed Extensions for Advanced Random Techniques: C++ Library and Applications for Random Number Generators
lang: en-US

baseurl: "/pxart-build2" # the subpath of your site, e.g. /blog/
url: https://lyrahgames.github.io # the base hostname & protocol for your site
git_address: https://github.com/lyrahgames/pxart-build2
git_edit_address: https://github.com/lyrahgames/pxart-build2/tree/master/docs

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: Spacelab

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: Europe/Berlin
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

- scope:
    path: _about
    type: about
  values:
    layout: about
    sectionid: about
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true
  about:
    permalink: /:collection/:path/
    output: true
