site_name: pXart
site_url: https://lyrahgames.github.io/pxart
repo_url: https://github.com/lyrahgames/pxart
edit_uri: edit/master/docs/main/docs
site_description: 'pXart: Packed Extensions for Advanced Random Techniques'
site_author: 'Markus Pawellek'
copyright: '2019, Markus Pawellek (markuspawellek@gmail.com)'

theme: cinder
docs_dir: docs
markdown_extensions:
  - markdown_include.include:
      base_path: docs

nav:
  - Home: index.md
  - About:
      - 'License': 'license.md'